version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: mitama_postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mitama
      - POSTGRES_USER=mitama
      - POSTGRES_PASSWORD=mitama
  mitama:
    image: mitama:latest-postgresql
    depends_on:
      - postgresql
    volumes:
      - "./:/project"
    ports:
      - 8080:80

