version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mitama_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mitama
      - MYSQL_PASSWORD=mitama
      - MYSQL_DATABASE=mitama
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  mitama:
    image: mitama:latest-mysql
    depends_on:
      - mysql
    volumes:
      - "./:/project"
    ports:
      - 8080:80
  
